### ISSUE TITLE
Procedures on how to install BRAWL PUBLIC GAME

### ISSUE THREAD

**Issue by farajihap70** [mitre/brawl-public-game-001#3]
hello, am new to malware analysis, especially on MITRE approach. I want to rub the BRAWL game, but i don't see any procedures on how to install it, could one help on this please.

**Comment by CraigWampler** [comment]
Hello @farajihap70!

The BRAWL data that was released is just data. There is currently no code you can install that has been released. I no longer work for MITRE, but if you send me a private message on Twitter (@ThwompWamp) with your e-mail address, I can forward it along to some co-workers that still work there and they may be able to get in touch and provide you with more information. It will also help if you can let me know what company/group/organization you are representing.

Cheers!

**Comment by CraigWampler** [comment]
@farajihap70  - as an aside, the README.md describes the format of the data. So you can use that to analyze the data in whatever tool you prefer - e.g. Elasticsearch, Splunk, IPython Notebook, etc
