### ISSUE TITLE
Brawl for Caldera

### ISSUE THREAD

**Issue by sulaimanbale11** [mitre/brawl-public-game-001#4]
Hi,

May i know how to setup BRAWL ? and how can i use BRAWL for CALDERA??

**Comment by CraigWampler** [comment]
Hello - BRAWL has only released a data set from a BRAWL game. I have stopped working for MITRE, but as far as I know, it has not been open sourced. 

Your best bet might be to contact the CALDERA team about easy ways to setup CALDERA to run in an environment. 

Cheers,
Craig
